// assert_exception.lzz
//

void throwAssertException (char const * exp, char const * file, int line)
{
  string path, name;
  file_op::getPathAndName (file, path, name);
  throw runtime_error (Message ("%:%: unexpected %") << name << line << exp);
}

using namespace std;

#hdr
#define AssertException(exp) (void) ( (exp) || (throwAssertException (#exp, __FILE__, __LINE__), 0) )
#end

#src
#include <util/file_op.h>
#include <util/message.h>
#include <stdexcept>
#end
